# docker-compose.yml
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://alagiyawanna101:Nd22tnlCzcxzZLBo@login.xk5ox.mongodb.net/?retryWrites=true&w=majority&appName=login
      - JWT_SECRET=your_jwt_secret_key
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./signin
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ./signin:/app