---
- name: Setup Docker and deploy app
  hosts: all
  become: yes
  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest
        update_only: yes

    - name: Install Docker dependencies
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install Docker
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create app directory
      file:
        path: /app
        state: directory

    - name: Copy project files
      copy:
        src: ../
        dest: /app/

    - name: Deploy application with Docker Compose
      command: docker-compose up -d
      args:
        chdir: /app