---
- name: Deploy Hotel Booking Application to EC2
  hosts: ec2_instances
  become: yes
  vars:
    mongo_uri: "{{ lookup('env', 'MONGO_URI') }}"
    jwt_secret: "{{ lookup('env', 'JWT_SECRET') }}"
  
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - docker.io
          - docker-compose
          - python3-docker
        state: present

    - name: Install Docker Python module
      apt:
        name: python3-docker
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Create application directory
      file:
        path: /opt/hotel-booking
        state: directory
        mode: '0755'

    - name: Create .env file
      copy:
        dest: /opt/hotel-booking/.env
        content: |
          MONGO_URI={{ mongo_uri }}
          JWT_SECRET={{ jwt_secret }}
        mode: '0600'

    - name: Copy docker-compose.yml template
      template:
        src: templates/docker-compose.yml.j2
        dest: /opt/hotel-booking/docker-compose.yml
        mode: '0644'

    - name: Login to DockerHub
      docker_login:
        username: "{{ lookup('env', 'DOCKERHUB_USERNAME') }}"
        password: "{{ lookup('env', 'DOCKERHUB_PASSWORD') }}"
      no_log: true

    - name: Pull latest Docker images
      shell: cd /opt/hotel-booking && docker-compose pull

    - name: Deploy application with docker-compose
      shell: cd /opt/hotel-booking && docker-compose up -d