---
- name: Deploy Hotel Booking Application to EC2
  hosts: ec2_instances
  become: true
  vars:
    mongo_uri: "{{ lookup('env', 'MONGO_URI') }}"
    jwt_secret: "{{ lookup('env', 'JWT_SECRET') }}"
    docker_registry: "kalagiyawanna"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - python3-docker
          - docker-compose
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create app directory
      file:
        path: /home/ubuntu/staysphere
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Create .env file
      copy:
        dest: /home/ubuntu/staysphere/.env
        content: |
          MONGO_URI={{ mongo_uri }}
          JWT_SECRET={{ jwt_secret }}
        mode: '0600'
        owner: ubuntu
        group: ubuntu

    - name: Create docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: /home/ubuntu/staysphere/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: "0644"

    - name: Pull Docker images
      docker_image:
        name: "{{ item }}"
        source: pull
      loop:
        - "{{ docker_registry }}/staysphere-backend:latest"
        - "{{ docker_registry }}/staysphere-signin:latest"

    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Reset ssh connection to allow user changes to affect the current session
      meta: reset_connection

    - name: Remove existing containers
      become: true
      become_user: ubuntu
      command: docker-compose down
      args:
        chdir: /home/ubuntu/staysphere
      ignore_errors: yes

    - name: Force recreate containers
      become: true
      become_user: ubuntu
      command: docker-compose up -d --force-recreate
      args:
        chdir: /home/ubuntu/staysphere

    - name: Verify containers are running
      become_user: ubuntu
      command: docker ps
      args:
        chdir: /home/ubuntu/staysphere
      register: docker_ps_result

    - name: Show running containers
      debug:
        var: docker_ps_result.stdout_lines